# repos contains helm repositories to be added
repos:
  # (optional) global username to be used for all repos
  username:
  # (optional) global password to be used for all repos
  password:
  add:
  - name: my_helm_repo
    remote: https://mydomain.com/my_helm_repo
    # (optional) override global username for this repo
    username:
    # (optional) override global password for this repo
    password:
  - name: stable
    remote: https://charts.helm.sh/stable


# charts from which the images must be parsed
charts:
  - repo: stable
    # name of the chart
    name: redis
    # (optional) overrides global fetch setting
    # from remote repository
    fetch: true
    # (optional) push specifies the list of target helm repositories to which
    # the chart should be pushed
    push:
      - my_helm_repo
    # (optional) Any custom scripts that should be run before running
    # any other action for this chart. The scripts would be run for 
    # each chart version
    scripts:
      - custom-hook1.sh arg1 arg2
      # When no arguments are provided repo-name, chart-name and version 
      # are passed as positional arguments by default
      - custom-hook2.sh
    # (optional) values to be passed to chart before rendering the templates
    # can be used for charts that have mandatorily required values
    values:
      # (optional) values to be passed to `--set` flag
      set:
      # (optional) values to be passed to `--set-string` flag
      set_str:
    versions:
      - version: 3.0.0
        # (optional) override fetch setting for version
        fetch: true
        # (optional) local_dir specifies the local directory in which the
        # chart tgz exists if fetch is set to false. It can also be
        # used to save the chart tgz file to desired local directory instead
        # of the default $PWD/tmp path.
        local_dir:
        # (optional) overrides push specified at chart level for the
        # current chart version
        push:
          - my_helm_repo
        # (optional) override values specified at chart level for current 
        # chart version
        values:
          # (optional) values to be passed to `--set` flag
          set:
          # (optional) values to be passed to `--set-string` flag
          set_str:


# registries specifies the docker registries to which the images must be pushed
registries:
  - name: hub.docker.com
    # (optional) the local tagged images will be retained if true else deleted after
    # pushing the image to the registty
    retain: false
    # (optional) images will not be pushed to the registry if set to false
    push: true


# init_scripts specifies any initilization scripts that must be run before starting the
# program. This can be used to enhance the functionality that is not available natively.
init_scripts:
  - init.sh


# Global settings

# (optional) fetch specifies the global fetch policy for all charts.
# defauls to true if not specified. If fetch is set to false, local_dir
# setting must be set to specify the local directory in which the charts exists
fetch: true

# (optional) push specifies the global push policy for all regitries.
# defaults to true if not specified. If push is set to false, images
# will not be pushed to specified registries
push: true

# (optional) retain specifies the global retain policy for all images
# defaults to false if not specified. if retain is set to false, images
# that are downloaded and retagged are deleted after pushing them
# to the specified registries
retain: false
