repos:
  username:
  password:
  add:
  - name: healthbot-helm-dev
    remote: https://svl-artifactory.juniper.net/artifactory/healthbot-helm-dev
    username:
    password:

charts:
  - fetch: true
    repo: healthbot-helm-dev
    name: config-manager
    versions:
      - fetch: true
        local_dir:
        version: 3.0.0-dev-24-g99f1ac8
fetch: true
pull_images: true
push: true
retain: true
init_scripts:
  - init.sh
registries:
  - name: svl-artifactory.juniper.net/healthbot-registry/helm/test
    retain: false
    push: true
